name: pvChat
main: com.purityvanilla.pvchat.PVChat
version: 1.0
api-version: 1.20
authors: [chiralpenguin]
description: Chat plugin for the Purity Vanilla Minecraft server
folia-supported: true
depend: [pvLib, pvCore]
commands:
  ignore:
    description: Adds/removes a player from your ignore list to block messages
    usage: /ignore <player>
    permission: pvchat.ignore
  ignorelist:
    description: Gives the list of usernames you currently have ignored
    usage: /ignorelist
    permission: pvchat.ignorelist
    aliases: [ignored]
  reload:
    description: Reloads the plugin's configs and messages
    usage: /pvchat-reload
    permission: pvchat.reload
permissions:
  pvchat.ignore.bypass:
    description: Chat and private messages will be sent regardless of if the recipient has the sender ignored
  pvchat.formatcodes.chat.all:
    description: Gives access to all formatting codes in chat
  pvchat.formatcodes.chat.magic:
    description: Gives access to magic (obfuscated) formatting in chat