name: pvChat
main: com.purityvanilla.pvchat.PVChat
version: 1.0
api-version: 1.20
authors: [chiralpenguin]
description: Chat plugin for the Purity Vanilla Minecraft server
folia-supported: true
depend: [pvLib, pvCore]
commands:
  reload:
    description: Reloads the plugin's configs and messages
    usage: /pvchat-reload
    permission: pvchat.reload
permissions:
  pvchat.formatcodes.chat.*:
    description: Gives access to all formatting codes in chat
  pvchat.formatcodes.chat.magic:
    description: Gives access to magic (obfuscated) formatting in chat